# name: Terraform Deploy

on:
  push:
    branches:
      - dev2
      - stage
  pull_request:
    branches:
      - stage


jobs:
  terraform-dev:
    if: github.ref_name == 'dev2'
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCLOUD_KEY_JSON }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="config/dev-us-central1/backend.conf" -force-copy -lock=false

      - name: Terraform Import Existing GCS Bucket
        if: env.CREATE_STATE_BUCKET == 'false'
        env:
          CREATE_STATE_BUCKET: false
        run: |
          terraform import -input=false \
            -var-file="config/dev-us-central1/terraform.tfvars" \
            module.buckets.google_storage_bucket.state_bucket[0] \
            terraform-tk-terra-dev

      - name: Export TF_VAR_google_credentials
        run: echo "TF_VAR_google_credentials='${{ secrets.GCLOUD_KEY_JSON }}'" >> $GITHUB_ENV


      - name: Terraform Plan
        run: terraform plan -var-file="config/dev-us-central1/terraform.tfvars" -input=false -no-color

      - name: Terraform Apply
        run: terraform apply -var-file="config/dev-us-central1/terraform.tfvars" -auto-approve


  terraform-stage:
    if: github.ref_name == 'stage'
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCLOUD_KEY_JSON_STAGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="backend-stage.conf"

      - name: Terraform Plan
        run: terraform plan -var-file="gcp-terra-testingtk/config/stage-us-central1/terraform-stage.tfvars"

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -var-file="terraform-stage.tfvars" -auto-approve